# Generated by Django 3.2.13 on 2022-04-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerinfo',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
